### PR TITLE
Remove unnecessary log exclusions and refactor controller.

### LINKED ISSUE #1248: Problems related to displaying/formatting incorrectly formatted coins
### What is your request about?

After [PR](https://github.com/Ctrlpanel-gg/panel/pull/1211) was merged in the last update, that which by the way was a big change, in some places the display of coins has not been updated, and they are displayed incorrectly.
This bug report aims to gather all the places where these errors exist, so that they can be corrected in the next version.

Current known:

- [x] When installing the panel, when creating the first user of the system, the initial credits are entered incorrectly in the DB.
- [x] On the administrator overview page, in the count of users' total coins.
- [x] Voucher modal success notification. [Screenshot here](https://github.com/Ctrlpanel-gg/panel/issues/1248#issuecomment-3033610007)
- [x] Admin user overview page. [Screenshot here](https://github.com/Ctrlpanel-gg/panel/issues/1248#issuecomment-3045968858)

### Branch

main

### Solution idea

_No response_

### CtrlPanel Logs

```Shell

```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Ferks-FK**
This PR fixes: #1264.
Note: The Referral notification class is in a new syntax, which was introduced by PR: #1257.
To work, the two PRs must be merged together.

### CODE REVIEW

File: app/Http/Controllers/Auth/RegisterController.php [hunk 1]
```diff
@@ -4,39 +4,33 @@
 
 use App\Http\Controllers\Controller;
 use App\Models\User;
-use App\Notifications\ReferralNotification;
 use App\Providers\RouteServiceProvider;
 use App\Traits\Referral;
-use Carbon\Carbon;
 use App\Settings\PterodactylSettings;
 use App\Classes\PterodactylClient;
```
Comment (kutistefanova9-art) [inline app/Http/Controllers/Auth/RegisterController.php:11]: Panel ff iOS

**Review by kutistefanova9-art — APPROVED** [review]

File: app/Http/Controllers/Auth/RegisterController.php (hunk 1 above)
Comment (MrWeez) [reply app/Http/Controllers/Auth/RegisterController.php:11]: What?

**Review by kutistefanova9-art — APPROVED** [review]

**Comment by 1day2die** [comment]
@Ferks-FK  can you post an update here on github?
