### PR TITLE
Fix api, and add api resource response.

### LINKED ISSUE #1248: Problems related to displaying/formatting incorrectly formatted coins
### What is your request about?

After [PR](https://github.com/Ctrlpanel-gg/panel/pull/1211) was merged in the last update, that which by the way was a big change, in some places the display of coins has not been updated, and they are displayed incorrectly.
This bug report aims to gather all the places where these errors exist, so that they can be corrected in the next version.

Current known:

- [x] When installing the panel, when creating the first user of the system, the initial credits are entered incorrectly in the DB.
- [x] On the administrator overview page, in the count of users' total coins.
- [x] Voucher modal success notification. [Screenshot here](https://github.com/Ctrlpanel-gg/panel/issues/1248#issuecomment-3033610007)
- [x] Admin user overview page. [Screenshot here](https://github.com/Ctrlpanel-gg/panel/issues/1248#issuecomment-3045968858)

### Branch

main

### Solution idea

_No response_

### CtrlPanel Logs

```Shell

```

### Additional Info

_No response_

### LINKED ISSUE #1256: The API layer is not updated.
### What is your request about?

The API part has not been updated to return the new credit format.

### Branch

main

### Solution idea

_No response_

### CtrlPanel Logs

```Shell

```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Ferks-FK**
Refactor all API endpoints to use JsonResource for responses.
As well as fix fields related to displaying and updating credits. (#1256)

it is necessary to decide on the maximum amount of credits a user can have on their account, in this PR it is currently set to 50K, this should be discussed before merging.

Due to the use of JsonResource in this PR's API responses, the format in which the data is delivered has changed slightly.
Responses from a list of resources, for example: `/api/users` now have more organized pagination fields and the user data comes within attribute “data” array.
Example:

```php
{
	"data": [
		{
			"id": 1,
			"name": "Ferks",
			"email": "t@t.com",
			"credits": 50000,
			"server_limit": 25,
                }
        ]
}
```
The same “data” attribute will be present on specific resource routes, such as `/api/users/1`.

Also adds nested includes that can be useful for user routes.
This makes it possible to do: `api/users?include=servers.product` and `api/users?include=vouchers.users`.

### CODE REVIEW

File: app/Http/Controllers/Api/BaseApiController.php
Comment (AVMG20) [inline app/Http/Controllers/Api/BaseApiController.php:1]: I dislike this class; not all API classes need this.
Using new CurrencyHelper() is also incorrect. You can use dependency injection for this, which makes the code easier to test in the future.
In any class where you need to use CurrencyHelper, you can add: __construct(protected CurrencyHelper $currencyHelper)
This will result in the class being automatically instantiated and usable in that class.

https://laravel.com/docs/12.x/container

File: app/Http/Controllers/Api/RoleController.php [hunk 1]
```diff
@@ -22,32 +17,23 @@ class RoleController extends Controller
     /**
      * Display a listing of the resource.
      *
-     * @return LengthAwarePaginator
+     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
```
Comment (AVMG20) [inline app/Http/Controllers/Api/RoleController.php]: should be RoleResource

File: app/Http/Controllers/Api/RoleController.php [hunk 2]
```diff
@@ -74,41 +60,31 @@ public function store(Request $request)
...
     }
 
     /**
      * Display the specified resource.
      *
      * @param  int  $id
-     * @return Role|Collection|Model
+     * @return RoleResource
      */
     public function show(int $id)
```
Comment (AVMG20) [inline app/Http/Controllers/Api/RoleController.php]: should not be int but be (Role $role) 
https://laravel.com/docs/12.x/routing#route-model-binding

File: app/Http/Controllers/Api/RoleController.php [hunk 3]
```diff
@@ -129,17 +105,16 @@ public function update(Request $request, int $id)
...
-        return $role;
+        return RoleResource::make($role);
     }
 
     /**
      * Remove the specified resource from storage.
      *
      * @param  int  $id
-     * @return Response
+     * @return RoleResource|\Illuminate\Http\JsonResponse
```
Comment (AVMG20) [inline app/Http/Controllers/Api/RoleController.php]: should just be RoleResource or the rest of the docs are incorrect?

File: app/Http/Controllers/Api/ServerController.php [hunk 4]
```diff
@@ -22,76 +19,92 @@ class ServerController extends Controller
      * Display a listing of the resource.
      *
      * @param  Request  $request
-     * @return LengthAwarePaginator
+     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
```
Comment (AVMG20) [inline app/Http/Controllers/Api/ServerController.php]: ServerResource

File: app/Http/Controllers/Api/ServerController.php [hunk 5]
```diff
@@ -22,76 +19,92 @@ class ServerController extends Controller
...
     /**
      * Display the specified resource.
      *
-     * @param  Server  $server
-     * @return Server|Collection|Model
+     * @param  string  $serverId
+     * @return ServerResource
      */
-    public function show(Server $server)
+    public function show(string $serverId)
```
Comment (AVMG20) [inline app/Http/Controllers/Api/ServerController.php]: Route binding
https://laravel.com/docs/12.x/routing#route-model-binding

File: app/Http/Controllers/Api/ServerController.php [hunk 6]
```diff
@@ -22,76 +19,92 @@ class ServerController extends Controller
...
     /**
      * Remove the specified resource from storage.
      *
-     * @param  Server  $server
-     * @return Server
+     * @param  string  $serverId
+     * @return ServerResource
      */
-    public function destroy(Server $server)
+    public function destroy(string $serverId)
```
Comment (AVMG20) [inline app/Http/Controllers/Api/ServerController.php]: https://laravel.com/docs/12.x/routing#route-model-binding

File: app/Http/Controllers/Api/ServerController.php [hunk 7]
```diff
@@ -22,76 +19,92 @@ class ServerController extends Controller
...
     /**
      * suspend server
      *
-     * @param  Server  $server
-     * @return Server|JsonResponse
+     * @param  string  $serverId
+     * @return ServerResource|JsonResponse
      */
-    public function suspend(Server $server)
+    public function suspend(string $serverId)
```
Comment (AVMG20) [inline app/Http/Controllers/Api/ServerController.php]: https://laravel.com/docs/12.x/routing#route-model-binding

File: app/Http/Controllers/Api/ServerController.php [hunk 8]
```diff
@@ -22,76 +19,92 @@ class ServerController extends Controller
...
+        return ServerResource::make($server);
     }
 
     /**
      * suspend server
      *
-     * @param  Server  $server
-     * @return Server|JsonResponse
+     * @param  string  $serverId
+     * @return ServerResource|JsonResponse
```
Comment (AVMG20) [inline app/Http/Controllers/Api/ServerController.php:159]: inconsistent doc

File: app/Http/Controllers/Api/ServerController.php [hunk 9]
```diff
@@ -22,76 +19,92 @@ class ServerController extends Controller
...
     /**
      * unsuspend server
      *
-     * @param  Server  $server
-     * @return Server|JsonResponse
+     * @param  string  $serverId
+     * @return ServerResource|JsonResponse
      */
-    public function unSuspend(Server $server)
+    public function unSuspend(string $serverId)
```
Comment (AVMG20) [inline app/Http/Controllers/Api/ServerController.php]: https://laravel.com/docs/12.x/routing#route-model-binding

File: app/Http/Controllers/Api/ServerController.php [hunk 10]
```diff
@@ -22,76 +19,92 @@ class ServerController extends Controller
...
+        return ServerResource::make($server);
     }
 
     /**
      * unsuspend server
      *
-     * @param  Server  $server
-     * @return Server|JsonResponse
+     * @param  string  $serverId
+     * @return ServerResource|JsonResponse
```
Comment (AVMG20) [inline app/Http/Controllers/Api/ServerController.php:246]: inconsistent doc

File: app/Http/Controllers/Api/UserController.php [hunk 11]
```diff
@@ -27,38 +27,41 @@
...
 use Spatie\QueryBuilder\QueryBuilder;
 
-class UserController extends Controller
+class UserController extends BaseApiController
 {
     private $pterodactyl;
 
     public function __construct(PterodactylSettings $ptero_settings)
     {
         $this->pterodactyl = new PterodactylClient($ptero_settings);
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php:42]: https://laravel.com/docs/12.x/container

File: app/Http/Controllers/Api/UserController.php [hunk 12]
```diff
@@ -27,38 +27,41 @@
...
+
+        parent::__construct();
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: if BaseApiController is removed this is no longer needed

File: app/Http/Controllers/Api/UserController.php [hunk 13]
```diff
@@ -27,38 +27,41 @@
...
 
+    const ALLOWED_INCLUDES = ['servers.product', 'notifications', 'payments', 'vouchers.users', 'roles', 'discordUser'];
     const ALLOWED_FILTERS = ['name', 'server_limit', 'email', 'pterodactyl_id', 'suspended'];
 
     /**
      * Display a listing of the resource.
      *
      * @param  Request  $request
-     * @return LengthAwarePaginator
+     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: UserResource

File: app/Http/Controllers/Api/UserController.php [hunk 14]
```diff
@@ -27,38 +27,41 @@
...
-        return $query->paginate($request->input('per_page') ?? 50);
+        return UserResource::collection($users);
     }
 
     /**
      * Display the specified resource.
      *
      * @param  int  $id
-     * @return User|Builder|Collection|Model
+     * @return UserResource|\Illuminate\Database\Eloquent\ModelNotFoundException
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: inconsistent

File: app/Http/Controllers/Api/UserController.php [hunk 15]
```diff
@@ -67,33 +70,36 @@ public function show(int $id)
...
         $discordUser = DiscordUser::find($id);
         $user = $discordUser ? $discordUser->user : User::findOrFail($id);
 
         $request->validate([
-            'name' => 'sometimes|string|min:4|max:30',
-            'email' => 'sometimes|string|email',
-            'credits' => 'sometimes|numeric|min:0|max:1000000',
+            'name' => 'required|string|min:4|max:30',
+            'email' => 'required|string|email',
+            'credits' => 'sometimes|numeric|min:0.01|max:50000',
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: why cap at 50k? what if my server uses values like 200k or even 2m?
Let admins who are using the API use it how they want to use it. there should not be any cap besides checking if the value does not exceed the Database limit

File: app/Http/Controllers/Api/UserController.php [hunk 16]
```diff
@@ -118,17 +124,18 @@ public function update(Request $request, int $id)
...
+        return UserResource::make($user);
     }
 
     /**
      * increments the users credits or/and server_limit
      *
      * @param  Request  $request
      * @param  int  $id
-     * @return User
+     * @return UserResource|\Illuminate\Database\Eloquent\ModelNotFoundException
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: inconsistent

File: app/Http/Controllers/Api/UserController.php [hunk 17]
```diff
@@ -138,38 +145,38 @@ public function increment(Request $request, int $id)
         $user = $discordUser ? $discordUser->user : User::findOrFail($id);
 
         $request->validate([
-            'credits' => 'sometimes|numeric|min:0|max:1000000',
+            'credits' => 'sometimes|numeric|min:0.01|max:50000',
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: why cap?

File: app/Http/Controllers/Api/UserController.php [hunk 18]
```diff
@@ -138,38 +145,38 @@ public function increment(Request $request, int $id)
...
             'server_limit' => 'sometimes|numeric|min:0|max:1000000',
         ]);
 
         if ($request->credits) {
-            if ($user->credits + $request->credits >= 99999999) {
+            if ($user->credits + $request->credits >= $this->currencyHelper->prepareForDatabase(50000)) {
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: minor complain: ($user->credits + $request->credits) >= $this->currencyHelper->prepareForDatabase(50000)
bit more readable in my opinion but optional.

File: app/Http/Controllers/Api/UserController.php [hunk 19]
```diff
@@ -138,38 +145,38 @@ public function increment(Request $request, int $id)
...
                 throw ValidationException::withMessages([
-                    'credits' => "You can't add this amount of credits because you would exceed the credit limit",
+                    'credits' => __("You can't add this amount of credits because you would exceed the credit limit"),
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: In my opinion, you should never translate any error messages in APIs since they're not meant for end-users but for admins connecting to the API. The field name (credits) is also not translated. It also makes looking in the code slightly more difficult since it won't lead you directly to the source but to the translation file.

File: app/Http/Controllers/Api/UserController.php [hunk 20]
```diff
@@ -138,38 +145,38 @@ public function increment(Request $request, int $id)
...
                 ]);
             }
             event(new UserUpdateCreditsEvent($user));
-            $user->increment('credits', $request->credits);
+            $user->increment('credits', $this->currencyHelper->prepareForDatabase($request->credits));
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: $preparedBalance = $this->currencyHelper->prepareForDatabase

this method is used twice now, it's long and makes the code long, this can be extracted to a variable on top.

File: app/Http/Controllers/Api/UserController.php [hunk 21]
```diff
@@ -138,38 +145,38 @@ public function increment(Request $request, int $id)
...
+        return UserResource::make($user->fresh());
     }
 
     /**
      * decrements the users credits or/and server_limit
      *
      * @param  Request  $request
      * @param  int  $id
-     * @return User
+     * @return UserResource|\Illuminate\Database\Eloquent\ModelNotFoundException
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: UserResource

File: app/Http/Controllers/Api/UserController.php [hunk 22]
```diff
@@ -179,78 +186,75 @@ public function decrement(Request $request, int $id)
         $user = $discordUser ? $discordUser->user : User::findOrFail($id);
 
         $request->validate([
-            'credits' => 'sometimes|numeric|min:0|max:1000000',
+            'credits' => 'sometimes|numeric|min:0.01|max:50000',
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: cap

File: app/Http/Controllers/Api/UserController.php [hunk 23]
```diff
@@ -179,78 +186,75 @@ public function decrement(Request $request, int $id)
...
             'server_limit' => 'sometimes|numeric|min:0|max:1000000',
         ]);
 
         if ($request->credits) {
-            if ($user->credits - $request->credits < 0) {
+            if ($user->credits - $this->currencyHelper->prepareForDatabase($request->credits) < 0) {
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: $this->currencyHelper->prepareForDatabase
can be extracted to variable

File: app/Http/Controllers/Api/UserController.php [hunk 24]
```diff
@@ -179,78 +186,75 @@ public function decrement(Request $request, int $id)
...
 
     /**
      * Suspends the user
      *
      * @param  Request  $request
      * @param  int  $id
-     * @return bool
-     *
-     * @throws ValidationException
+     * @return UserResource|\Illuminate\Http\JsonResponse|\Illuminate\Database\Eloquent\ModelNotFoundException
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: UserResource

File: app/Http/Controllers/Api/UserController.php [hunk 25]
```diff
@@ -179,78 +186,75 @@ public function decrement(Request $request, int $id)
...
     public function suspend(Request $request, int $id)
     {
         $discordUser = DiscordUser::find($id);
         $user = $discordUser ? $discordUser->user : User::findOrFail($id);
 
         if ($user->isSuspended()) {
-            throw ValidationException::withMessages([
-                'error' => 'The user is already suspended',
-            ]);
+            return response()->json([
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php:210]: This can be simplified to: response('text', 400)
 Laravel will automatically convert to JSON if the user has this in their request headers.

File: app/Http/Controllers/Api/UserController.php [hunk 26]
```diff
@@ -179,78 +186,75 @@ public function decrement(Request $request, int $id)
...
 
     /**
      * Unsuspend the user
      *
      * @param  Request  $request
      * @param  int  $id
-     * @return bool
-     *
-     * @throws ValidationException
+     * @return UserResource|\Illuminate\Http\JsonResponse|\Illuminate\Database\Eloquent\ModelNotFoundException
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: UserResource

File: app/Http/Controllers/Api/UserController.php [hunk 27]
```diff
@@ -179,78 +186,75 @@ public function decrement(Request $request, int $id)
...
     public function unsuspend(Request $request, int $id)
     {
         $discordUser = DiscordUser::find($id);
         $user = $discordUser ? $discordUser->user : User::findOrFail($id);
 
         if (! $user->isSuspended()) {
-            throw ValidationException::withMessages([
-                'error' => 'You cannot unsuspend an User who is not suspended.',
-            ]);
+            return response()->json([
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php:242]: response()

File: app/Http/Controllers/Api/UserController.php [hunk 28]
```diff
@@ -337,14 +345,14 @@ public function store(Request $request, UserSettings $userSettings)
...
     }
 
     /**
      * Remove the specified resource from storage.
      *
      * @param  int  $id
-     * @return Application|Response|ResponseFactory
+     * @return UserResource|\Illuminate\Database\Eloquent\ModelNotFoundException
      */
     public function destroy(int $id)
```
Comment (AVMG20) [inline app/Http/Controllers/Api/UserController.php]: [route binding](https://laravel.com/docs/12.x/routing#route-model-binding)

File: app/Http/Controllers/Api/VoucherController.php [hunk 29]
```diff
@@ -21,131 +16,90 @@ class VoucherController extends Controller
...
      */
     public function store(Request $request)
     {
-        $request->validate([
+        $data = $request->validate([
             'memo' => 'nullable|string|max:191',
             'code' => 'required|string|alpha_dash|max:36|min:4|unique:vouchers',
             'uses' => 'required|numeric|max:2147483647|min:1',
-            'credits' => 'required|numeric|between:0,99999999',
+            'credits' => 'required|numeric|min:0.01|max:50000',
```
Comment (AVMG20) [inline app/Http/Controllers/Api/VoucherController.php]: wierd cap, already explained in other feedback

File: app/Http/Controllers/Api/VoucherController.php [hunk 30]
```diff
@@ -21,131 +16,90 @@ class VoucherController extends Controller
...
+
+        return VoucherResource::make($voucher);
     }
 
     /**
      * Display the specified resource.
      *
      * @param  int  $id
-     * @return Voucher|Collection|Model
+     * @return VoucherResource|\Illuminate\Database\Eloquent\ModelNotFoundException
```
Comment (AVMG20) [inline app/Http/Controllers/Api/VoucherController.php]: inconsistent doc

File: app/Http/Controllers/Api/VoucherController.php [hunk 31]
```diff
@@ -21,131 +16,90 @@ class VoucherController extends Controller
...
+        return VoucherResource::make($voucher);
     }
 
     /**
      * Update the specified resource in storage.
      *
      * @param  Request  $request
      * @param  int  $id
-     * @return Response
+     * @return VoucherResource|\Illuminate\Database\Eloquent\ModelNotFoundException
```
Comment (AVMG20) [inline app/Http/Controllers/Api/VoucherController.php]: inconsistent doc

File: app/Http/Controllers/Api/VoucherController.php [hunk 32]
```diff
@@ -21,131 +16,90 @@ class VoucherController extends Controller
...
     {
         $voucher = Voucher::findOrFail($id);
 
-        $request->validate([
+        $data = $request->validate([
             'memo' => 'nullable|string|max:191',
             'code' => "required|string|alpha_dash|max:36|min:4|unique:vouchers,code,{$voucher->id}",
             'uses' => 'required|numeric|max:2147483647|min:1',
-            'credits' => 'required|numeric|between:0,99999999',
+            'credits' => 'required|numeric|min:0.01|max:50000',
```
Comment (AVMG20) [inline app/Http/Controllers/Api/VoucherController.php]: wierd cap

File: app/Http/Controllers/Api/VoucherController.php [hunk 33]
```diff
@@ -21,131 +16,90 @@ class VoucherController extends Controller
...
     }
 
     /**
      * Remove the specified resource from storage.
      *
      * @param  int  $id
-     * @return Response
+     * @return VoucherResource|\Illuminate\Database\Eloquent\ModelNotFoundException
      */
     public function destroy(int $id)
```
Comment (AVMG20) [inline app/Http/Controllers/Api/VoucherController.php]: [route binding](https://laravel.com/docs/12.x/routing#route-model-binding)

File: app/Http/Resources/BaseJsonResource.php [hunk 34]
```diff
@@ -0,0 +1,18 @@
+<?php
+
+namespace App\Http\Resources;
+
+use App\Helpers\CurrencyHelper;
+use Illuminate\Http\Resources\Json\JsonResource;
+
+class BaseJsonResource extends JsonResource
```
Comment (AVMG20) [inline app/Http/Resources/BaseJsonResource.php]: No need for this class, already explained at BaseAPIController

File: app/Http/Resources/RoleResource.php [hunk 35]
```diff
@@ -0,0 +1,27 @@
...
+    public function toArray(Request $request): array
+    {
+        return [
+            'id' => $this->id,
+            'name' => $this->name,
+            'color' => $this->color,
+            'power' => $this->power,
+            'created_at' => $this->created_at->toDateTimeString(),
+            'updated_at' => $this->updated_at->toDateTimeString(),
+            'permissions' => PermissionResource::collection($this->whenLoaded('permissions')),
```
Comment (AVMG20) [inline app/Http/Resources/RoleResource.php:26]: Nice

File: app/Http/Resources/UserResource.php [hunk 36]
```diff
@@ -0,0 +1,42 @@
+<?php
+
+namespace App\Http\Resources;
+
+use Illuminate\Http\Request;
+
+class UserResource extends BaseJsonResource
```
Comment (AVMG20) [inline app/Http/Resources/UserResource.php]: Just a tip: you can add the @mixin docblock on top for better type hinting and click-through for the editor:

@mixin App\Models\User

This will tell the editor that this class is also the User class, which it kind of is in Laravel, making $this refer to User.

Great for resource classes

**Review by AVMG20 — CHANGES_REQUESTED** [review]
Good changes! I like the implementation of resource classes—this helps a lot with consistency in the API.

Besides some minor issues, it's a good PR for making the API better!

File: app/Models/Role.php [hunk 37]
```diff
@@ -11,6 +12,21 @@
...
+     * Determine if the role can be deleted.
+     * 
+     * @return bool
+     */
+    public function isDeletable(): bool
+    {
+        return !in_array($this->id, [
+            Roles::ADMIN_ROLE_ID,
+            Roles::SUPPORT_TEAM_ROLE_ID,
+            Roles::CLIENT_ROLE_ID
```
Comment (1day2die) [inline app/Models/Role.php:26]: shouldnt we add the use rrole here aswell?=

**Comment by 1day2die** [comment]
@Ferks-FK  can you post an update here on github?

**Comment by Ferks-FK** [comment]
After further analyzing the purpose of the PR, I decided to remove the API documentation using the scribe.
Because this is a fix PR.
